### ISSUE TITLE
Error to start 

### ISSUE THREAD

**Issue by dsakura** [camenduru/Fooocus-colab#17]
```
Downloading: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0_0.9vae.safetensors" to /content/Fooocus-MRE/models/checkpoints/sd_xl_base_1.0_0.9vae.safetensors

Traceback (most recent call last):
  File "/content/Fooocus-MRE/entry_with_update.py", line 46, in <module>
    from launch import *
  File "/content/Fooocus-MRE/launch.py", line 145, in <module>
    download_models()
  File "/content/Fooocus-MRE/launch.py", line 102, in download_models
    load_file_from_url(url=url, model_dir=modelfile_path, file_name=file_name)
  File "/content/Fooocus-MRE/modules/model_loader.py", line 24, in load_file_from_url
    download_url_to_file(url, cached_file, progress=progress)
  File "/usr/local/lib/python3.10/dist-packages/torch/hub.py", line 620, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

Many thanks!

**Comment by Metatronarc** [comment]
Same issue here, yesterday it was working smoothly. Thanks!
